LODGenerator: MainWindow Class Reference
MainWindow Class Reference
#include <MainWindow.h>
Public Member Functions
MainWindow (QWidget *parent=0)
~MainWindow ()
Private Slots
void on_loadB_clicked ()
void on_m_lods_clicked (const QModelIndex &index)
void on_deleteLODB_clicked ()
void on_createLODB_clicked ()
void on_exportAllB_clicked ()
void on_exportLODB_clicked ()
Private Attributes
Ui::MainWindow * m_ui
GLWindow * m_gl
our openGL widget
Detailed Description
Definition at line 11 of file MainWindow.h.
Constructor & Destructor Documentation
MainWindow::MainWindow (QWidget * parent = 0) [explicit]
Definition at line 11 of file MainWindow.cpp.
References m_gl, and m_ui.
                                      :
  QMainWindow(parent),
  m_ui(new Ui::MainWindow)
{
  m_ui->setupUi(this);
  QGLFormat format;
  // set the number of samples for multisampling
  // will need to enable glEnable(GL_MULTISAMPLE); once we have a context
  format.setSamples(4);
  #if defined( DARWIN)
    // at present mac osx Mountain Lion only supports GL3.2
    // the new mavericks will have GL 4.x so can change
    format.setVersion(3,2);
  #else
    // with luck we have the latest GL version so set to this
    format.setVersion(4,5);
  #endif
  // now we are going to set to CoreProfile OpenGL so we can't use and old Immediate mode GL
  format.setProfile(QGLFormat::CoreProfile);
  // now set the depth buffer to 24 bits
  format.setDepthBufferSize(24);
  m_gl=new GLWindow(format, this);
  m_ui->s_mainWindowGridLayout->addWidget(m_gl,0,0,2,1);
  connect(m_ui->m_wireframe,SIGNAL(toggled(bool)),m_gl,SLOT(toggleWireframe(bool)));
}
MainWindow::~MainWindow ()
Definition at line 41 of file MainWindow.cpp.
References m_ui.
{
  delete m_ui;
}
Member Function Documentation
void MainWindow::on_createLODB_clicked () [private, slot]
Definition at line 127 of file MainWindow.cpp.
References GLWindow::allModels, GLWindow::createLOD(), GLWindow::extUpdateGL(), GLWindow::getLODs(), m_gl, m_ui, SSTR, and GLWindow::updateAllLODs().
{
  m_gl->createLOD(m_ui->nFaces->value());
  QString id = SSTR(m_gl->getLODs().size()).c_str();
  m_gl->updateAllLODs();
  m_ui->m_lods->addItem(id);
  m_ui->m_lods->setCurrentRow(m_gl->allModels.size()-1);
  m_gl->extUpdateGL();
}
void MainWindow::on_deleteLODB_clicked () [private, slot]
Definition at line 114 of file MainWindow.cpp.
References GLWindow::extUpdateGL(), m_gl, GLWindow::m_selectedModel, m_ui, and GLWindow::updateAllLODs().
{
  if (m_ui->m_lods->currentRow() != 0)
  {
    //delete(m_gl->m_lods[m_gl->m_selectedModel]);
    m_ui->m_lods->takeItem(m_ui->m_lods->currentRow());
    m_gl->m_selectedModel = 0;
    m_ui->m_lods->setCurrentRow(0);
    m_gl->updateAllLODs();
    m_gl->extUpdateGL();
  }
}
void MainWindow::on_exportAllB_clicked () [private, slot]
Definition at line 137 of file MainWindow.cpp.
References GLWindow::exportAllLOD(), and m_gl.
{
    m_gl->exportAllLOD();
}
void MainWindow::on_exportLODB_clicked () [private, slot]
Definition at line 142 of file MainWindow.cpp.
References GLWindow::exportLOD(), m_gl, and m_ui.
{
    m_gl->exportLOD(m_ui->m_lods->currentRow());
}
void MainWindow::on_loadB_clicked () [private, slot]
Definition at line 46 of file MainWindow.cpp.
References GLWindow::file, GLWindow::filepath, GLWindow::getModelLODTri(), m_gl, GLWindow::m_lods, GLWindow::m_selectedModel, m_ui, GLWindow::setModelLOD(), and GLWindow::updateAllLODs().
{
  QFileDialog dialog(this);
  dialog.setFileMode(QFileDialog::ExistingFile);
  QStringList filters;
  filters << tr("Obj (*.obj)") << tr("All Files (*)");
  dialog.setNameFilters(filters);
  dialog.setViewMode(QFileDialog::Detail);
  QStringList fileNames;
  if(dialog.exec())
  {
    fileNames = dialog.selectedFiles();
  }
  if (fileNames.size() > 0)
  {
    QString fileName = fileNames.at(0);
    std::cout << fileName.toLocal8Bit().constData() <<std::endl;
    std::cout << fileName.size()-fileName.lastIndexOf("/") << std::endl;
    QString file = fileName.split("/",QString::SkipEmptyParts).back().split(".",QString::SkipEmptyParts).front();
    QStringList fileNameFull = fileName.split("/",QString::SkipEmptyParts);
    QString path = "/";
    for (int i = 0; i < fileNameFull.size()-1; ++i)
    {
      path.append(fileNameFull.at(i));
      path.append("/");
    }
    std::cout<<path.toLocal8Bit().constData()<<std::endl;
    m_gl->m_lods.clear();
    m_ui->pathLE->setText(fileName);
    m_ui->fileNameL->setText(file);
    m_gl->filepath = path.toLocal8Bit().constData();
    m_gl->file = file.toLocal8Bit().constData();
    m_gl->setModelLOD(fileName.toLocal8Bit().constData());
    m_ui->nFaces->setMaximum(m_gl->getModelLODTri()->getNumFaces()-1);
    m_ui->nFaces->setValue(m_gl->getModelLODTri()->getNumFaces()-1);
    m_ui->m_lods->setCurrentRow(m_gl->m_selectedModel);
    m_gl->updateAllLODs();
  }
}
void MainWindow::on_m_lods_clicked (const QModelIndex & index) [private, slot]
Definition at line 92 of file MainWindow.cpp.
References GLWindow::extUpdateGL(), GLWindow::getLODs(), GLWindow::getModelLODTri(), m_gl, GLWindow::m_selectedModel, and m_ui.
{
  std::string str = index.data().toString().toLocal8Bit().constData();
  if (str == "BaseMesh")
  {
    if (m_gl->getModelLODTri() != NULL)
    {
      m_ui->nFaces->setMaximum(m_gl->getModelLODTri()->getNumFaces()-1);
      m_ui->nFaces->setValue(m_gl->getModelLODTri()->getNumFaces()-1);
    }
  }
  else
    {
    m_ui->nFaces->setMaximum(m_gl->getLODs()[m_gl->m_selectedModel]->getNumFaces()-1);
    m_ui->nFaces->setValue(m_gl->getLODs()[m_gl->m_selectedModel]->getNumFaces()-1);
    }
  m_gl->m_selectedModel = m_ui->m_lods->currentRow();
  m_gl->extUpdateGL();
}
Member Data Documentation
GLWindow* MainWindow::m_gl [private]
our openGL widget
Definition at line 36 of file MainWindow.h.
Ui::MainWindow* MainWindow::m_ui [private]
Definition at line 33 of file MainWindow.h.
The documentation for this class was generated from the following files:
MainWindow.h
MainWindow.cpp