LODGenerator: Triangle Class Reference
Triangle Class Reference
used to store face/triangle information for ModelLOD
#include <TriangleV.h>
Public Member Functions
Triangle (int _id)
default id constructor
Triangle (Vertex *_v0, Vertex *_v1, Vertex *_v2)
default vertex constructor
Triangle (int _id, Vertex *_v0, Vertex *_v1, Vertex *_v2)
default id and vertex constructor
Triangle (const Triangle &_t)
copy ctor
virtual ~Triangle ()
deconstructor
virtual Triangle * clone () const
deep copy of the Triangle class
bool operator== (const Triangle &_t) const
check for equality uses FCompare (from Util.h) as float values
bool operator!= (const Triangle &_t) const
not equal check
Triangle & operator= (Triangle &_t)
assignment operator set the current vecrtex to rhs
int getID ()
get Triangle id
void setID (int _id)
set Triangle id
int getNormID (int _pos)
get normal id for the vert
void setNormID (int _id, int _pos)
set norm id
int getTexID (int _pos)
get tex id
void setTexID (int _id, unsigned int _pos)
set tex id
ngl::Vec4 getFaceNormal ()
get Triangle normal
void calculateNormal ()
calculates normal and stores in m_fNormal
bool hasVert (Vertex *_v)
finds out if the triangle has a particular vertex or not
void replaceVertex (Vertex *_u, Vertex *_v)
updates the face, replacing all of Vertex _u with _v
Public Attributes
std::vector< Vertex * > m_vert
vector of three Vertex vertices that make up the triangle
std::vector< ngl::Vec3 > m_norm
vector of the three normal values for each vertex in the triangle
std::vector< ngl::Vec3 > m_tex
vector of the three texture co-ordinate values for each vertex in the triangle
bool m_textureCoord
boolean that says if the vertex has texture co-ordinates or not
bool m_normals
boolean that is true if the vertex has normals or not
Protected Attributes
ngl::Vec4 m_fNormal
the face normal
int m_id
the triangle id
std::vector< int > m_normID
vector of each normalID for each value in m_norm (respectively)
std::vector< int > m_texID
vector of each textureID for each value in m_tex (respectively)
Detailed Description
used to store face/triangle information for ModelLOD
Author:
Jonathan Flynn
Version:
1.0
Date:
14/05/15 completed a working version of the class
Definition at line 199 of file TriangleV.h.
Constructor & Destructor Documentation
Triangle::Triangle (int _id) [inline]
default id constructor
Parameters:
[in] _id id number for the face
Definition at line 207 of file TriangleV.h.
                     :
    m_id(_id){;}
  //----------------------------------------------------------------------------------------------------------------------
Triangle::Triangle (Vertex * _v0, Vertex * _v1, Vertex * _v2) [inline]
default vertex constructor
Parameters:
[in] _v0 vertex zero
[in] _v1 vertex one
[in] _v2 vertex two
Definition at line 215 of file TriangleV.h.
References m_vert.
  {
    m_vert.reserve(3);
    m_vert[0]=_v0;
    m_vert[1]=_v1;
    m_vert[2]=_v2;
  }
Triangle::Triangle (int _id, Vertex * _v0, Vertex * _v1, Vertex * _v2) [inline]
default id and vertex constructor
Parameters:
[in] _id id number for the face
[in] _v0 vertex zero
[in] _v1 vertex one
[in] _v2 vertex two
Definition at line 229 of file TriangleV.h.
References m_id, and m_vert.
  {
    m_id = _id;
    m_vert.reserve(3);
    m_vert[0]=_v0;
    m_vert[1]=_v1;
    m_vert[2]=_v2;
  }
Triangle::Triangle (const Triangle & _t) [inline]
copy ctor
Definition at line 241 of file TriangleV.h.
                                :
    m_norm(_t.m_norm),
    m_tex(_t.m_tex),
    m_textureCoord(_t.m_textureCoord),
    m_normals(_t.m_normals),
    m_fNormal(_t.m_fNormal),
    m_id(_t.m_id),
    m_normID(_t.m_normID),
    m_texID(_t.m_texID){;}
  //----------------------------------------------------------------------------------------------------------------------
Triangle::~Triangle () [virtual]
deconstructor
Definition at line 112 of file TriangleV.cpp.
References m_vert.
{
  for (unsigned int i=0; i<3; ++i)
  {
    if (m_vert[i])
    {
      m_vert[i]->remAdjFace(this);
    }
  }
  for (unsigned int i=0; i<3; ++i)
  {
    int i2 = (i+1)%3;
    if(!m_vert[i] || !m_vert[i2]) continue;
    m_vert[i]->remIfNonNeighbour(m_vert[i2]);
    m_vert[i2]->remIfNonNeighbour(m_vert[i]);
  }
}
Member Function Documentation
void Triangle::calculateNormal ()
calculates normal and stores in m_fNormal
Parameters:
[in] _verts the m_vertex list for the ModelLODTri class to access the vertex co-ordinates
Definition at line 180 of file TriangleV.cpp.
References m_fNormal, and m_vert.
{
  // create two vectors v and w from the triangle's points
  ngl::Real v[3] = {( m_vert[1]->m_vert.m_x - m_vert[0]->m_vert.m_x ),
                    ( m_vert[1]->m_vert.m_y - m_vert[0]->m_vert.m_y ),
                    ( m_vert[1]->m_vert.m_z - m_vert[0]->m_vert.m_z )};
  ngl::Real w[3] = {( m_vert[2]->m_vert.m_x - m_vert[0]->m_vert.m_x ),
                    ( m_vert[2]->m_vert.m_y - m_vert[0]->m_vert.m_y ),
                    ( m_vert[2]->m_vert.m_z - m_vert[0]->m_vert.m_z )};
  // cross product the two vectors
  m_fNormal.m_x = (v[1]*w[2]) - (v[2]*w[1]);
  m_fNormal.m_y = (v[2]*w[0]) - (v[0]*w[2]);
  m_fNormal.m_z = (v[0]*w[1]) - (v[1]*w[0]);
  // if the length is zero, don't normalize
  if (m_fNormal.length() != 0)
  {
    m_fNormal.normalize();
  }
}
virtual Triangle* Triangle::clone () const [inline, virtual]
deep copy of the Triangle class
Returns:
Triangle* to a copy of the current Triangle class
Definition at line 258 of file TriangleV.h.
References Triangle().
{return (new Triangle(*this));}
ngl::Vec4 Triangle::getFaceNormal () [inline]
get Triangle normal
Returns:
a Vec4 containing the vector of the triangle normal
Definition at line 311 of file TriangleV.h.
References m_fNormal.
{ return m_fNormal; }
int Triangle::getID () [inline]
get Triangle id
Returns:
an int being the Triangle ID in the m_face list
Definition at line 281 of file TriangleV.h.
References m_id.
{ return m_id; }
int Triangle::getNormID (int _pos) [inline]
get normal id for the vert
Returns:
an int being the Traingle ID in the m_face list
Definition at line 291 of file TriangleV.h.
References m_normID.
{ return m_normID[_pos]; }
int Triangle::getTexID (int _pos) [inline]
get tex id
Returns:
an int being the Traingle ID in the m_face list
Definition at line 301 of file TriangleV.h.
References m_texID.
{ return m_texID[_pos]; }
bool Triangle::hasVert (Vertex * _v)
finds out if the triangle has a particular vertex or not
Parameters:
[in] _v the pointer to the vertex to check if it exists in the triangle
Definition at line 201 of file TriangleV.cpp.
References m_vert.
{
  std::vector< Vertex *>::iterator it;
  it = std::find(m_vert.begin(), m_vert.end(), _v);
  return (it != m_vert.end());
}
bool Triangle::operator!= (const Triangle & _t) const
not equal check
Parameters:
[in] _v the vertex to check against
Returns:
true of false
Definition at line 140 of file TriangleV.cpp.
References m_id, and m_vert.
{
  return (_t.m_id != m_id ||
          _t.m_vert[0] != m_vert[0] ||
          _t.m_vert[1] != m_vert[1] ||
          _t.m_vert[2] != m_vert[2]);
}
Triangle & Triangle::operator= (Triangle & _t)
assignment operator set the current vecrtex to rhs
Parameters:
[in] _v the vertex to set
Returns:
a new vertex
Definition at line 149 of file TriangleV.cpp.
References m_id, and m_vert.
{
  m_vert = _t.m_vert;
  m_id = _t.m_id;
  return *this;
}
bool Triangle::operator== (const Triangle & _t) const
check for equality uses FCompare (from Util.h) as float values
Parameters:
[in] _v the vertex to check against
Returns:
true or false
Definition at line 131 of file TriangleV.cpp.
References m_id, and m_vert.
{
  return (_t.m_id == m_id &&
          _t.m_vert[0] == m_vert[0] &&
          _t.m_vert[1] == m_vert[1] &&
          _t.m_vert[2] == m_vert[2]);
}
void Triangle::replaceVertex (Vertex * _u, Vertex * _v)
updates the face, replacing all of Vertex _u with _v
Parameters:
[in] _u the pointer to the vertex you want to replace
[in] _v the pointer to the vertex you want to use to replace
Definition at line 208 of file TriangleV.cpp.
References Vertex::addAdjFace(), calculateNormal(), Vertex::hasAdjFace(), m_vert, Vertex::remAdjFace(), and Vertex::remIfNonNeighbour().
{
  assert(_u && _v);
  assert(_u == m_vert[0] || _u == m_vert[1] || _u == m_vert[2]);
  assert(_v != m_vert[0] && _v != m_vert[1] && _v != m_vert[2]);
  std::vector< Vertex *>::iterator it;
  it = std::find(m_vert.begin(), m_vert.end(), _u);
  if (it != m_vert.end())
  {
    m_vert[std::distance(m_vert.begin(), it)] = _v;
  }
  _u->remAdjFace(this);
  assert(!_v->hasAdjFace(this));
  _v->addAdjFace(this);
  for (unsigned int i=0; i<3; i++)
  {
    _u->remIfNonNeighbour(m_vert[i]);
    m_vert[i]->remIfNonNeighbour(_u);
  }
  for (unsigned int i=0; i<3; i++)
  {
    assert(m_vert[i]->hasAdjFace(this)==1);
    for(unsigned int j=0; j<3; j++)
    {
      if (i != j &&
          std::find(m_vert.begin(), m_vert.end(), _v) != m_vert.end() &&
          !m_vert[i]->hasAdjVert(m_vert[j]))
      {
          m_vert[i]->m_vertAdj.push_back(m_vert[j]);
      }
    }
  }
  calculateNormal();
}
void Triangle::setID (int _id) [inline]
set Triangle id
Parameters:
[in] _id int to set the id to
Definition at line 286 of file TriangleV.h.
References m_id.
{ m_id = _id; }
void Triangle::setNormID (int _id, int _pos)
set norm id
Parameters:
[in] _id int to set the id to
Definition at line 156 of file TriangleV.cpp.
References m_normID.
{
  if (m_normID.size()+1 > _pos)
  {
    m_normID.push_back(_id);
  }
  else
  {
    m_normID[_pos] = _id;
  }
}
void Triangle::setTexID (int _id, unsigned int _pos)
set tex id
Parameters:
[in] _id int to set the id to
Definition at line 168 of file TriangleV.cpp.
References m_texID.
{
  if (m_texID.size()+1 > _pos)
  {
    m_texID.push_back(_id);
  }
  else
  {
    m_texID[_pos] = _id;
  }
}
Member Data Documentation
ngl::Vec4 Triangle::m_fNormal [protected]
the face normal
Definition at line 355 of file TriangleV.h.
int Triangle::m_id [protected]
the triangle id
Definition at line 359 of file TriangleV.h.
std::vector<ngl::Vec3> Triangle::m_norm
vector of the three normal values for each vertex in the triangle
Definition at line 335 of file TriangleV.h.
bool Triangle::m_normals
boolean that is true if the vertex has normals or not
Definition at line 347 of file TriangleV.h.
std::vector<int> Triangle::m_normID [protected]
vector of each normalID for each value in m_norm (respectively)
Definition at line 363 of file TriangleV.h.
std::vector<ngl::Vec3> Triangle::m_tex
vector of the three texture co-ordinate values for each vertex in the triangle
Definition at line 339 of file TriangleV.h.
std::vector<int> Triangle::m_texID [protected]
vector of each textureID for each value in m_tex (respectively)
Definition at line 367 of file TriangleV.h.
bool Triangle::m_textureCoord
boolean that says if the vertex has texture co-ordinates or not
Definition at line 343 of file TriangleV.h.
std::vector<Vertex *> Triangle::m_vert
vector of three Vertex vertices that make up the triangle
Definition at line 331 of file TriangleV.h.
The documentation for this class was generated from the following files:
TriangleV.h
TriangleV.cpp